[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Florian Maas <fpgmaas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8,<4.0"
pandas = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
